name: CI

on:
  push:
      branches: [develop]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install formula
        run: cp other/*-iina.rb $(brew --repo homebrew/core)/Formula

      - name: Install dependencies
        run: make depends

      - name: Build
        run: make build

      - name: Create .dmg file
        run: |
          brew install create-dmg
          make dmg

      - uses: actions/upload-artifact@v2
        with:
          name: IINA
          path: IINA.dmg
